In [2]:
import pandas as pd
import numpy as np

In [5]:
data_order = pd.read_excel('../data/项目1_commerce_order_2025.xlsx')
data_order

,行 ID,订单ID,产品id,客户 ID,发货日期,国家,地区,城市,子类别,客户名称,...,细分,订单日期,销售经理,利润,折扣,数量,是否退回,计划发货天数,销售额,实际发货时间
0,1,4870971,秋装—秋衣—2874,邢宁-18715,2024-01-03,中国,中南,常德,秋衣,邢宁,...,公司,2024-01-01,王倩倩,610.680,0.0,3,1,3,1607.340,2
1,2,4870971,冬装—围巾—1047,邢宁-18715,2024-01-03,中国,中南,常德,围巾,邢宁,...,公司,2024-01-01,王倩倩,1321.600,0.0,5,1,3,3304.700,2
2,3,4479160,冬装—羽绒服—0928,康青-19585,2024-01-03,中国,中南,广州,羽绒服,康青,...,消费者,2024-01-01,王倩倩,2.800,0.0,2,0,1,286.720,2
3,4,3231478,夏装—长裙—2425,谭珊-19900,2024-01-03,中国,华北,天津,长裙,谭珊,...,消费者,2024-01-01,张怡莲,118.440,0.0,2,0,3,456.120,2
4,5,3231478,夏装—长裙—2425,谭珊-19900,2024-01-03,中国,华北,天津,长裙,谭珊,...,消费者,2024-01-01,张怡莲,194.600,0.0,5,0,3,591.500,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9901,9902,1637441,冬装—手套—0574,杨栋-12340,2025-12-31,中国,华北,北京,手套,杨栋,...,公司,2025-12-30,张怡莲,7.420,0.0,1,0,1,68.600,1
9902,9903,4162714,夏装—短袖—1460,韦绅-20005,2025-12-31,中国,中南,武汉,短袖,韦绅,...,消费者,2025-12-30,王倩倩,-178.948,0.4,7,1,1,3574.452,1
9903,9904,4162714,冬装—羽绒服—0928,韦绅-20005,2025-12-31,中国,中南,武汉,羽绒服,韦绅,...,消费者,2025-12-30,王倩倩,341.600,0.0,5,1,1,697.900,1
9904,9905,4162714,秋装—外套—4928,韦绅-20005,2025-12-31,中国,中南,武汉,外套,韦绅,...,消费者,2025-12-30,王倩倩,-1391.040,0.4,5,0,1,2454.060,1
9905,9906,4084381,秋装—秋衣—2874,王丹-12010,2025-12-31,中国,华北,海拉尔,秋衣,王丹,...,消费者,2025-12-31,张怡莲,-146.160,0.4,4,1,0,2914.800,0

In [12]:
# 利润四分位
Q1 = data_order['利润'].quantile(0.25)
Q3 = data_order['利润'].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

In [16]:
# 利润异常值
data_order['利润异常值标记'] = 0
data_order.loc[data_order['利润'] > upper_bound, '利润异常值标记'] = 1
data_order.loc[data_order['利润'] < lower_bound, '利润异常值标记'] = -1
data_order

,行 ID,订单ID,产品id,客户 ID,发货日期,国家,地区,城市,子类别,客户名称,...,订单日期,销售经理,利润,折扣,数量,是否退回,计划发货天数,销售额,实际发货时间,利润异常值标记
0,1,4870971,秋装—秋衣—2874,邢宁-18715,2024-01-03,中国,中南,常德,秋衣,邢宁,...,2024-01-01,王倩倩,610.680,0.0,3,1,3,1607.340,2,0
1,2,4870971,冬装—围巾—1047,邢宁-18715,2024-01-03,中国,中南,常德,围巾,邢宁,...,2024-01-01,王倩倩,1321.600,0.0,5,1,3,3304.700,2,1
2,3,4479160,冬装—羽绒服—0928,康青-19585,2024-01-03,中国,中南,广州,羽绒服,康青,...,2024-01-01,王倩倩,2.800,0.0,2,0,1,286.720,2,0
3,4,3231478,夏装—长裙—2425,谭珊-19900,2024-01-03,中国,华北,天津,长裙,谭珊,...,2024-01-01,张怡莲,118.440,0.0,2,0,3,456.120,2,0
4,5,3231478,夏装—长裙—2425,谭珊-19900,2024-01-03,中国,华北,天津,长裙,谭珊,...,2024-01-01,张怡莲,194.600,0.0,5,0,3,591.500,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9901,9902,1637441,冬装—手套—0574,杨栋-12340,2025-12-31,中国,华北,北京,手套,杨栋,...,2025-12-30,张怡莲,7.420,0.0,1,0,1,68.600,1,0
9902,9903,4162714,夏装—短袖—1460,韦绅-20005,2025-12-31,中国,中南,武汉,短袖,韦绅,...,2025-12-30,王倩倩,-178.948,0.4,7,1,1,3574.452,1,0
9903,9904,4162714,冬装—羽绒服—0928,韦绅-20005,2025-12-31,中国,中南,武汉,羽绒服,韦绅,...,2025-12-30,王倩倩,341.600,0.0,5,1,1,697.900,1,0
9904,9905,4162714,秋装—外套—4928,韦绅-20005,2025-12-31,中国,中南,武汉,外套,韦绅,...,2025-12-30,王倩倩,-1391.040,0.4,5,0,1,2454.060,1,-1
9905,9906,4084381,秋装—秋衣—2874,王丹-12010,2025-12-31,中国,华北,海拉尔,秋衣,王丹,...,2025-12-31,张怡莲,-146.160,0.4,4,1,0,2914.800,0,0

In [19]:
# 准时到货
data_order['是否超时'] = 0
# 超时到货
data_order.loc[data_order['实际发货时间'] > data_order['计划发货天数'], '是否超时'] = 1
# 提前到货
data_order.loc[data_order['实际发货时间'] < data_order['计划发货天数'], '是否超时'] = -1
data_order

,行 ID,订单ID,产品id,客户 ID,发货日期,国家,地区,城市,子类别,客户名称,...,销售经理,利润,折扣,数量,是否退回,计划发货天数,销售额,实际发货时间,利润异常值标记,是否超时
0,1,4870971,秋装—秋衣—2874,邢宁-18715,2024-01-03,中国,中南,常德,秋衣,邢宁,...,王倩倩,610.680,0.0,3,1,3,1607.340,2,0,-1
1,2,4870971,冬装—围巾—1047,邢宁-18715,2024-01-03,中国,中南,常德,围巾,邢宁,...,王倩倩,1321.600,0.0,5,1,3,3304.700,2,1,-1
2,3,4479160,冬装—羽绒服—0928,康青-19585,2024-01-03,中国,中南,广州,羽绒服,康青,...,王倩倩,2.800,0.0,2,0,1,286.720,2,0,1
3,4,3231478,夏装—长裙—2425,谭珊-19900,2024-01-03,中国,华北,天津,长裙,谭珊,...,张怡莲,118.440,0.0,2,0,3,456.120,2,0,-1
4,5,3231478,夏装—长裙—2425,谭珊-19900,2024-01-03,中国,华北,天津,长裙,谭珊,...,张怡莲,194.600,0.0,5,0,3,591.500,2,0,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9901,9902,1637441,冬装—手套—0574,杨栋-12340,2025-12-31,中国,华北,北京,手套,杨栋,...,张怡莲,7.420,0.0,1,0,1,68.600,1,0,0
9902,9903,4162714,夏装—短袖—1460,韦绅-20005,2025-12-31,中国,中南,武汉,短袖,韦绅,...,王倩倩,-178.948,0.4,7,1,1,3574.452,1,0,0
9903,9904,4162714,冬装—羽绒服—0928,韦绅-20005,2025-12-31,中国,中南,武汉,羽绒服,韦绅,...,王倩倩,341.600,0.0,5,1,1,697.900,1,0,0
9904,9905,4162714,秋装—外套—4928,韦绅-20005,2025-12-31,中国,中南,武汉,外套,韦绅,...,王倩倩,-1391.040,0.4,5,0,1,2454.060,1,-1,0
9905,9906,4084381,秋装—秋衣—2874,王丹-12010,2025-12-31,中国,华北,海拉尔,秋衣,王丹,...,张怡莲,-146.160,0.4,4,1,0,2914.800,0,0,0

In [21]:
# 销售额四分位
Q1_SALES = data_order['销售额'].quantile(0.25)
Q3_SALES = data_order['销售额'].quantile(0.75)

IQR_SALES = Q3_SALES - Q1_SALES

lower_bound_SALES = Q1_SALES - 1.5 * IQR_SALES
upper_bound_SALES = Q3_SALES + 1.5 * IQR_SALES
# 销售额异常值
data_order['销售额异常值标记'] = 0
data_order.loc[data_order['销售额'] > upper_bound_SALES, '销售额异常值标记'] = 1
data_order.loc[data_order['销售额'] < lower_bound_SALES, '销售额异常值标记'] = -1
data_order

,行 ID,订单ID,产品id,客户 ID,发货日期,国家,地区,城市,子类别,客户名称,...,利润,折扣,数量,是否退回,计划发货天数,销售额,实际发货时间,利润异常值标记,是否超时,销售额异常值标记
0,1,4870971,秋装—秋衣—2874,邢宁-18715,2024-01-03,中国,中南,常德,秋衣,邢宁,...,610.680,0.0,3,1,3,1607.340,2,0,-1,0
1,2,4870971,冬装—围巾—1047,邢宁-18715,2024-01-03,中国,中南,常德,围巾,邢宁,...,1321.600,0.0,5,1,3,3304.700,2,1,-1,0
2,3,4479160,冬装—羽绒服—0928,康青-19585,2024-01-03,中国,中南,广州,羽绒服,康青,...,2.800,0.0,2,0,1,286.720,2,0,1,0
3,4,3231478,夏装—长裙—2425,谭珊-19900,2024-01-03,中国,华北,天津,长裙,谭珊,...,118.440,0.0,2,0,3,456.120,2,0,-1,0
4,5,3231478,夏装—长裙—2425,谭珊-19900,2024-01-03,中国,华北,天津,长裙,谭珊,...,194.600,0.0,5,0,3,591.500,2,0,-1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9901,9902,1637441,冬装—手套—0574,杨栋-12340,2025-12-31,中国,华北,北京,手套,杨栋,...,7.420,0.0,1,0,1,68.600,1,0,0,0
9902,9903,4162714,夏装—短袖—1460,韦绅-20005,2025-12-31,中国,中南,武汉,短袖,韦绅,...,-178.948,0.4,7,1,1,3574.452,1,0,0,0
9903,9904,4162714,冬装—羽绒服—0928,韦绅-20005,2025-12-31,中国,中南,武汉,羽绒服,韦绅,...,341.600,0.0,5,1,1,697.900,1,0,0,0
9904,9905,4162714,秋装—外套—4928,韦绅-20005,2025-12-31,中国,中南,武汉,外套,韦绅,...,-1391.040,0.4,5,0,1,2454.060,1,-1,0,0
9905,9906,4084381,秋装—秋衣—2874,王丹-12010,2025-12-31,中国,华北,海拉尔,秋衣,王丹,...,-146.160,0.4,4,1,0,2914.800,0,0,0,0

In [24]:
data_order.to_csv('../data/commerce_order_alter.csv', index=False, encoding='utf-8-sig')
data_order

,行 ID,订单ID,产品id,客户 ID,发货日期,国家,地区,城市,子类别,客户名称,...,利润,折扣,数量,是否退回,计划发货天数,销售额,实际发货时间,利润异常值标记,是否超时,销售额异常值标记
0,1,4870971,秋装—秋衣—2874,邢宁-18715,2024-01-03,中国,中南,常德,秋衣,邢宁,...,610.680,0.0,3,1,3,1607.340,2,0,-1,0
1,2,4870971,冬装—围巾—1047,邢宁-18715,2024-01-03,中国,中南,常德,围巾,邢宁,...,1321.600,0.0,5,1,3,3304.700,2,1,-1,0
2,3,4479160,冬装—羽绒服—0928,康青-19585,2024-01-03,中国,中南,广州,羽绒服,康青,...,2.800,0.0,2,0,1,286.720,2,0,1,0
3,4,3231478,夏装—长裙—2425,谭珊-19900,2024-01-03,中国,华北,天津,长裙,谭珊,...,118.440,0.0,2,0,3,456.120,2,0,-1,0
4,5,3231478,夏装—长裙—2425,谭珊-19900,2024-01-03,中国,华北,天津,长裙,谭珊,...,194.600,0.0,5,0,3,591.500,2,0,-1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9901,9902,1637441,冬装—手套—0574,杨栋-12340,2025-12-31,中国,华北,北京,手套,杨栋,...,7.420,0.0,1,0,1,68.600,1,0,0,0
9902,9903,4162714,夏装—短袖—1460,韦绅-20005,2025-12-31,中国,中南,武汉,短袖,韦绅,...,-178.948,0.4,7,1,1,3574.452,1,0,0,0
9903,9904,4162714,冬装—羽绒服—0928,韦绅-20005,2025-12-31,中国,中南,武汉,羽绒服,韦绅,...,341.600,0.0,5,1,1,697.900,1,0,0,0
9904,9905,4162714,秋装—外套—4928,韦绅-20005,2025-12-31,中国,中南,武汉,外套,韦绅,...,-1391.040,0.4,5,0,1,2454.060,1,-1,0,0
9905,9906,4084381,秋装—秋衣—2874,王丹-12010,2025-12-31,中国,华北,海拉尔,秋衣,王丹,...,-146.160,0.4,4,1,0,2914.800,0,0,0,0